### PR TITLE
Fix footer overflow

### PR DESCRIPTION
**Pull request by samarsault**
https://github.com/fossasia/fossasia11/issues/44

### CODE REVIEW

**Comment by samarsault** [comment]
@mariobehling can you close the issues fixed earlier ? in https://github.com/fossasia/fossasia11/pull/46 and https://github.com/fossasia/fossasia11/pull/45

**Comment by mariobehling** [comment]
screenshot from 2015-01-14 12 34 22
Great Flickr area looks good. Please also check footer. Thank you

**Comment by samarsault** [comment]
@mariobehling what's the resolution you're using above ?

**Comment by mariobehling** [comment]
The resolution does not matter. You can try this out, if you make the window smaller.

**Comment by samarsault** [comment]
screen shot 2015-01-14 at 5 08 46 pm
check this ^ it is how it appears on my phone did you check http://samarjeet27.github.io/fossasia11/

**Comment by samarsault** [comment]
@mariobehling also, what are you talking about here https://github.com/fossasia/fossasia11/issues/33 ?

**Comment by mariobehling** [comment]
Ahh ok. I see. This issue appears on Firefox. Chromium is fine here.

**Comment by samarsault** [comment]
@mariobehling can the issues be closed ?

**Comment by mariobehling** [comment]
The question is, if this can also be fixed for firefox?

**Comment by samarsault** [comment]
also, @mariobehling https://github.com/fossasia/fossasia11/issues/33, the site already has a mobile menu -
screen shot 2015-01-14 at 5 24 29 pm

**Comment by mariobehling** [comment]
I am starting to get confused. Let's keep the conversation in each issue to the issue topic. I attend the issues whenever I can.

**Comment by samarsault** [comment]
@mariobehling oh :) then please answer the queries in the issues whenever you can :)

**Pull request merged**
