### PR TITLE
First Draft of site

### PR DESCRIPTION
**Pull request by samarsault**

### CODE REVIEW

**Comment by namangoel1** [comment]
Is this to be hosted on gh-pages? Can I see the task? Thanks!

**Comment by namangoel1** [comment]
Also @mariobehling @samarjeet27 , if this is going to be on gh-pages, then `_site` needs to be in .gitignore. I suggest you create a new pull request.

**Comment by roonyh** [comment]
@samarjeet27 Thanks! good work! can you please make the pull request to the gh-pages branch? Its good if you work on gh-pages branch, on your fork as well, so we can see your site online.

@namangoel1 see tasks titled "Develop a jekyll site with..."

**Comment by samarsault** [comment]
@RoonyH forgot about that :)
will make it asap :)

**Comment by namangoel1** [comment]
Do add `_site` to gitignore, since gh will be overwriting it when building.

**Pull request merged**
